image:
  file: .gitpod.Dockerfile
tasks:
  - command: Rscript graph.R && open Rplots.pdf
vscode:
  extensions:
    - Mikhail-Arkhipov.r@0.0.6:M4pd3IjUdOlW1oU7q8SITA==
    - Ikuyadeu.r@1.2.1:z5vr1v1bfS++U/aHLSXQ6Q==
